#!/bin/bash -e

TRANSCRIPTION_DIR=/usr/local/bigbluebutton/core/lib/transcription

case "$1" in
  purge)
    rm -f "${TRANSCRIPTION_DIR}/transcription.yml"
  ;;

  remove|disappear|upgrade|failed-upgrade|abort-install|abort-upgrade)
  ;;

  *)
    echo "## postrm called with unknown argument \`$1'" >&2
  ;;
esac
