bbb_version: '3.0.9'
raw_audio_src: /var/freeswitch/meetings
mediasoup_video_src: /var/mediasoup/recordings
mediasoup_screenshare_src: /var/mediasoup/screenshare
webrtc_recorder_video_src: /var/lib/bbb-webrtc-recorder/recordings
webrtc_recorder_screenshare_src: /var/lib/bbb-webrtc-recorder/screenshare
webrtc_recorder_audio_src: /var/lib/bbb-webrtc-recorder/audio
raw_deskshare_src: /var/bigbluebutton/deskshare
raw_presentation_src: /var/bigbluebutton
notes_endpoint: http://127.0.0.1:9002/p
notes_formats:
  - etherpad
  - html
  - pdf
redis_host: 127.0.0.1
redis_port: 6379
store_recording_status: false
anonymize_chat: false
anonymize_chat_moderators: false
show_moderator_viewpoint: false
steps:
  archive: "sanity"
  sanity: "captions"
  captions:
    - 'process:presentation'
    - 'process:notes'
    - 'process:video'
  'process:presentation': 'publish:presentation'
  'process:notes': 'publish:notes'
  'process:video': 'publish:video'

# For LOCAL DEVELOPMENT - Override paths to use local directories
log_dir: /home/ubuntu/bbb-playback-ai/logs
recording_dir: /home/ubuntu/bbb-playback-ai/recording
published_dir: /home/ubuntu/bbb-playback-ai/recording/publish
playback_host: ovh-test.meetbbb.com
playback_protocol: https
