---
name: "Build .deb package"
on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  release:
    types: [created]

jobs:
  build-deb-package:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Full history needed for dch_version.sh git describe

      - name: Build Debian package
        uses: ./.github/actions/build-deb-package

  release:
    name: "Upload assets to release"
    needs: build-deb-package
    runs-on: ubuntu-22.04
    if: ${{ github.event_name == 'release' }}
    permissions:
      contents: write
      actions: read
    steps:
      - uses: actions/checkout@v4

      - uses: actions/download-artifact@v4
        with:
          name: "bbb-record-ai-summary-ubuntu-22.04"
          path: "artifacts"

      - name: Upload release assets
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: gh release upload ${{ github.event.release.tag_name }} artifacts/*.deb
