---
name: "📦 Build .deb package"
on:
  push:
    branches: ["ai-summary-new-format"]
    tags: ["v*"]
  pull_request:
    branches: ["ai-summary-new-format"]

jobs:
  build-deb-package:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Full history needed for dch_version.sh git describe

      - name: Build Debian package
        uses: ./.github/actions/build-deb-package

  release:
    name: "Upload assets to release"
    needs: build-deb-package
    runs-on: ubuntu-22.04
    if: ${{ github.ref_type == 'tag' }}
    permissions:
      contents: write
      actions: read
    steps:
      - uses: actions/checkout@v4

      - uses: actions/download-artifact@v4
        with:
          name: "bbb-record-ai-summary-ubuntu-22.04"
          path: "bbb-record-ai-summary-ubuntu-22.04"

      - name: Create release asset archive
        run: zip --junk-paths --recurse-paths --compression-method store "bbb-record-ai-summary-ubuntu-22.04.zip" "bbb-record-ai-summary-ubuntu-22.04"

      - name: Upload release assets
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: gh release upload ${{ github.ref_name }} "bbb-record-ai-summary-ubuntu-22.04.zip"
